version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  Minimal-Test:
    docker:
      - image: python:3.5
    steps:
      - checkout
      - run:
          name: Install
          command: |
            pip install -r requirements.txt
            pip install pytest
      - run:
          name: Test
          command: pytest

  Advanced-Test:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
          name: Install
          command: |
            pip install -r dev-requirements.txt
      - run:
          name: Test
          command: |
            black --check .
            pytest --cov=expandvars
      - run:
          name: Codecov
          command: |
            bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  Install-And-Test:
    jobs:
      - Minimal-Test
      - Advanced-Test
